### ISSUE TITLE
when an app is hidden, clicking the icon from the menu bar does not reveal the app

### ISSUE THREAD

**Issue by jaycverg** [EthanSK/Menu-Bar-Dock#1]
Steps to reproduce:
1. Open a browser
2. Press cmd + H
3. Click the browser's icon from the menu bar
4. Notice that the menu bar reflects the app's menus but does not show the app

**Comment by EthanSK** [comment]
Hi, just right click one of the menu bar icons, and open up preferences. Then click the "launch an application instead of activating". Maybe I should've made this the default behaviour, but both have their quirks

**Comment by jaycverg** [comment]
I see. Thanks!
Btw, great work!

**Comment by jaycverg** [comment]
@EthanSK, I will leave this issue closed but maybe you can take a look. Somehow, it doesn't work for Finder. All other apps I use have no problem, like my IDE, browser, and iTerm.

**Comment by EthanSK** [comment]
Yeah, I found that finder works differently to all other apps. I tried to account for it specifically, but I guess I didn't cover all cases. I'm open to accepting pull requests 😁

**Comment by EthanSK** [comment]
I felt nice and updated it, now it should work with finder, lemme know if it doesn't :p
