### ISSUE TITLE
Right side of menu bar under left side (of menu bar)

### ISSUE THREAD

**Issue by Rafsonn** [EthanSK/Menu-Bar-Dock#14]
Hi :). Since the new macbook pro has a really wide menu bar, all the icons on the right side can be moved to the second row on the left side. Then the dock on the right side would have more space and I think it would look cleaner (the left side would be a bit of a mess, but you could just hide a few icons under the '...' icon like the bartender for Mac).
If it is too much work or you do not like the idea, I will try to implement it someday (I don't even have my new mac yet :D) ... Unfortunately I do not have any experience with swift or this kind of apps yet. 

Regards, Rafał

**Comment by EthanSK** [comment]
what exactly do you mean by second row on the left side?

**Comment by Rafsonn** [comment]
It is hard to write it even simpler but let me try ... Suppose you are using chrome. On the left side at the top you see the apple logo, "chrome", "file" and so on. On the right you see icons, battery, date, etc. The idea is to leave the right side as it is and move everything on the right side under what is on the left (i.e. apple logo, "chrome", "file" and under that - icons, battery, date ...)

**Comment by EthanSK** [comment]
Hmm..this seems like a whole different project and undertaking. That would require the menu bar icons to be outside the menu bar. I see what you mean, the menu bar is much taller on new macs, but Apple still provide the same API for the menu bar, and for us developers, the menu bar height is still the exact same as it used to be, so it would be impossible to change that using Apple official APIs.
