### ISSUE TITLE
[Inquiry] App still being maintained?

### ISSUE THREAD

**Issue by Laicure** [EthanSK/Menu-Bar-Dock#26]
This is what I have been looking for!
Coming from Windows, I hate the Dock! It's like a 3rd-party app taking precious space on your monitor!

I hope this app is still being maintained.

Onyx's semi perma-hide Dock (Dock still shows on Launchpad and still toggle-able) + this app = perfect!
No need to use Stage Manager anymore!

**Comment by EthanSK** [comment]
well yes but it shouldn't break any time soon since using official apple apis

**Comment by Laicure** [comment]
I see, good to know and more apps from you, kind sir!
