### ISSUE TITLE
Feature request: Keep order and keep active app in menubar

### ISSUE THREAD

**Issue by cjke** [EthanSK/Menu-Bar-Dock#3]
Very cool app. 

Would it be possible to keep the order (same as the dock maintains its order) - something as simple as alphabetical order would suffice (just to stop it juggling around while in use)?
In a similar way, could it also keep the current app in the menu, again to stop it juggling around while in use

(edit: I'd be open to a PR but I'm not a Swift dev)

**Comment by gitnixpie** [comment]
I agree. The juggling is a bit chaotic and ordering the icons with cmd becomes redundant as soon as you switch apps.

**Comment by EthanSK** [comment]
Done :) https://github.com/EthanSK/Menu-Bar-Dock/releases/tag/3.0
