### ISSUE TITLE
Feature request: Option to hide certain apps

### ISSUE THREAD

**Issue by milesmcclane** [EthanSK/Menu-Bar-Dock#5]
Hi there,

What a great little tool. Thanks! I'm trying to use it to give apps that don't have them, a menu bar icon. Because of this I don't really want or need all open apps to be visible in the menu bar. 

I use bartender and have played around with hiding the ones I don't want etc, which works to a point. However it also shows some unexpected behaviours, like replacing say 'Reeder' which I want available all the time, with say 'Safari', when I open it up for a search. Ideally I would like certain apps visible and stay consistently where I put them, and I want most others not to even show up. This use case probably isn't the intended use case, but what do you think of adding the option? Is it doable?

Cheers,

Miles

**Comment by EthanSK** [comment]
Check out the latest version of the app. I completely overhauled it, it might have the features you are looking for now

**Comment by milesmcclane** [comment]
Yeah really cool! It now does exactly what I need! Thanks for the hard work -  I’ll close this issue.
