### ISSUE TITLE
Feature Request: Greyscale or Whiten Icons

### ISSUE THREAD

**Issue by shouyang** [EthanSK/Menu-Bar-Dock#6]
Hey there,

Really cool app! 

Would love to see an option for app icons to fit to the black and white theme a lot of menu bar icons have. I wonder if its easy to run the dock icons through a grey-scale filter and boost the contrast to that effect.

**Comment by EthanSK** [comment]
This is quite complex and niche, so it's probably not on the roadmap for the foreseeable future, but you can find some code and make a PR if you wish!
